<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>CrispMic</AssemblyName>
    <RootNamespace>CrispMic</RootNamespace>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <Product>CrispMic</Product>
    <Version>1.0.1</Version>
    <Authors>xander</Authors>
    <Description>Ultra-lightweight native audio preamplifier and neural noise suppressor for Windows</Description>
    <NoWarn>$(NoWarn);WFO1000;CS0618</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NAudio.Wasapi" Version="22.0.0" />
    <PackageReference Include="YellowDogMan.RRNoise.NET" Version="0.1.9" />
  </ItemGroup>

</Project>